.generate: $(wildcard *.py)
	touch .generate
	-rm -f include/*u.h gensrc/*u.{txt,cpp} gensrc/*u_.cpp
	-python apigenerate.py /usr/include/w32api/windows.h
	-python crtgenerate.py /usr/i686-w64-mingw32/sys-root/mingw/include msvcrt.h
