.generate: $(wildcard *.py)
	touch .generate
	-rm -f *u.txt *u.cpp *u_.cpp *u.h
	-python apigenerate.py /usr/include/w32api/windows.h
	-python crtgenerate.py /usr/i686-w64-mingw32/sys-root/mingw/include msvcrt.h
